### ISSUE TITLE
Malware Kit RegEx

### ISSUE THREAD

**Issue by Ne0nd0g** [0xZDH/redirect.rules#2]
The Regular Expressions in the Malware Kit section do not escape spaces or `(`. This generates a lot of errors that keeps Apache from starting while using the rules.

Two Examples:
```
   RewriteCond             %{HTTP_USER_AGENT}                  ^.*(bot.*$ [OR,NC]
   RewriteCond             %{HTTP_USER_AGENT}                  ^.*download express.*$ [OR,NC]

```

**Comment by 0xZDH** [comment]
Good catch. This also made me realize a few other potential RegEx errors that I cleaned up as well. Just pushed fixes via 4efe9e1a026b6e0886e2999efb075d3671b15b0c

**Comment by Ne0nd0g** [comment]
Thanks for the quick turn around!

You might also recommend installing `whois` on the readme. It was on the servers I provisioned by default.

**Comment by 0xZDH** [comment]
Great point! I updated the README requirements to install whois as well as enable mod_rewrite on Apache via 1981be6bceedf0e696a2c4d262371224e7c49c5e
