### ISSUE TITLE
Mobile redirection 

### ISSUE THREAD

**Issue by rzmpzgeviii** [0xZDH/redirect.rules#6]
Hi there, i´ve been testing sneaky proxy by @puzzlepeaches which is using your redirect rules. Everything works like a charm except on mobile. When a victim clicks on the link via a mobile device he is getting redirected wrongly.  But only on mobile.

What do u might think could redirect only mobile to the wrong endpoint? 

Kind regards!

**Comment by 0xZDH** [comment]
It is difficult to identify the exact reason of redirection without more information. The majority of the redirects are network based with the exception of some rules like User-Agent redirection. If the victim is using an Android-based mobile device, the User-Agent could contain a keyword like `Linux` which would trigger a hit against the denied User-Agent list (e.g. an example Android User-Agent starts with `Mozilla/5.0 (Linux; U; Android 4.4.2; en-us;`, which contains the Linux keyword for getting redirected).

You can remove the linux wild card in the `redirect.rules` file by searching for and removing the line containing: `^.*linux.*$`

If you wanted to debug manually, on the system that is using redirect.rules, you can enable verbose logging by editing the `redirect.rules` file (should be line 27 or similar) and uncommenting `#LogLevel alert rewrite:trace5` by removing the `#` at the start of the line. Restart the apache service and this will take affect and your apache log files should include and indicate which rule was met that is causing the redirection.

**Comment by puzzlepeaches** [comment]
To second @0xZDH, the ruleset here isn't foolproof. It is best during an engagement to be ready to modify rules on the fly. In  sneaky_proxy, you can tail the containers logs to watch what rule is triggering undesired redirects. Then, exec into the container and modify the redirect.rules file and restart the Apache service.

Alternatively, make modifications to the exclude folder [here](https://github.com/puzzlepeaches/sneaky_proxy/tree/main/exclude) and rebuild the container.
